# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TvbOAGzXc2Mj0W_B24V5pWvL9gsyr1jc
"""

class Persona:
    def __init__(self, nombre, documento):
        self._nombre = nombre
        self._documento = documento

    @property
    def nombre(self):
        return self._nombre

    @property
    def documento(self):
        return self._documento

class Turno:
    def __init__(self, persona, numero):
        self._persona = persona
        self._numero = numero

    @property
    def persona(self):
        return self._persona

    @property
    def numero(self):
        return self._numero

class CajaAtencion:
    def __init__(self):
        self._turnos = []
        self._contador = 0

    def agregar_persona(self, persona):
        self._contador += 1
        nuevo_turno = Turno(persona, self._contador)
        self._turnos.append(nuevo_turno)
        print(f"Turno #{nuevo_turno.numero} asignado a {persona.nombre}")

    def atender_siguiente(self):
        if self.esta_vacia():
            print("No hay nadie en la cola")
            return None

        turno_atendido = self._turnos.pop(0)
        print(f"Atendiendo a {turno_atendido.persona.nombre} (Turno #{turno_atendido.numero})")
        return turno_atendido

    def esta_vacia(self):
        return len(self._turnos) == 0

    def proximo_turno(self):
        if self.esta_vacia():
            print("Cola vacía")
            return None
        siguiente = self._turnos[0]
        print(f"Próximo turno: #{siguiente.numero} - {siguiente.persona.nombre}")
        return siguiente

def main():
    caja = CajaAtencion()

    # Crear 4 personas
    personas = [
        Persona("Carlos Pérez", "1204567822"),
        Persona("Luisa Jimenez", "0965432112"),
        Persona("Javier Ortega", "1122334450"),
        Persona("Roberto Saltos", "1724332211")]

    # Registrar llegadas
    print("--- Llegada de personas ---")
    for persona in personas:
        caja.agregar_persona(persona)

    print("\n--- Mostrar próximo turno ---")
    caja.proximo_turno()

    # Atención de persona de 2 en 2
    grupo = 1
    while not caja.esta_vacia():
        print(f"\n--- Atendiendo grupo {grupo} (2 personas) ---")


        for _ in range(2):
            if caja.esta_vacia():
                break
            caja.atender_siguiente()

        if not caja.esta_vacia():
            print("\n--- Próximo turno después del grupo ---")
            caja.proximo_turno()
        else:
            print("\n--- Todas las personas han sido atendidas ---")
            caja.proximo_turno()

        grupo += 1

if __name__ == "__main__":
    main()